import * from "./char.ab"
import * from "./testing.ab"

fun test_char_is_one_of() {
    test_section("test_char_is_one_of")

    test_expectation("it should always return false when a list is empty")
    assert(not char_is_one_of("a", [Text]), "false expected")?
    assert(not char_is_one_of("!", [Text]), "false expected")?

    test_expectation("it should return true when c is in chars")
    assert(char_is_one_of("a", ["a", "b", "c"]), "true expected")?
    assert(char_is_one_of("b", ["a", "b", "c"]), "true expected")?
    assert(char_is_one_of("c", ["a", "b", "c"]), "true expected")?

    test_expectation("it should return false when c is not in chars")
    assert(not char_is_one_of("d", ["a", "b", "c"]), "false expected")?
}

pub fun test_char() {
    test_char_is_one_of()?
}

main {
    test_char()?
}
