import * from "./error.ab"
import * from "./object.ab"
import * from "./env.ab"
import * from "./runtime_corelib.ab"
import * from "./testing.ab"
import * from "./eval_test_utils.ab"

fun test_runtime_corelib_base_cons() {
    test_section("test_runtime_corelib_base_cons")
    test_expectation("it should make a cons-cell")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    let pair = new_cons(new_text("a"), new_num(123))
    env = env_define(env, new_symbol("pair"), pair)
    assert_exprs_equal("(cons \"a\" 123)", "pair", env)?
}

main {
    test_runtime_corelib_base_cons()?
}