
import * from "./error.ab"
import * from "./object.ab"
import * from "./env.ab"
import * from "./runtime_corelib.ab"
import * from "./testing.ab"
import * from "./eval_test_utils.ab"

fun test_runtime_corelib_base_error() {
    test_section("test_runtime_corelib_base_error")
    test_expectation("it should raise an error")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    assert_expr_raises_err("(error \"foo\")", code_user_error(), env)?
    assert_expr_raises_err("(error \"my_error\" \"foo\")", "my_error", env)?
}

fun test_runtime_corelib_base_exit() {
    test_section("test_runtime_corelib_base_exit")
    test_expectation("it should raise exit_interpreter")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    assert_expr_raises_err("(exit)", code_exit_interpreter(), env)?
}

fun test_runtime_corelib_base_eqv() {
    test_section("test_runtime_corelib_base_eqv")
    test_expectation("it should return whether the given objects are the same")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    let pair = new_num(2)
    pair = new_cons(new_num(1), pair)
    env = env_define(env, new_symbol("pair"), pair)
    assert_exprs_equal("(eqv? 1 1)", "t", env)?
    assert_exprs_equal("(eqv? 1 2)", "nil", env)?
    assert_exprs_equal("(eqv? \"foo\" \"foo\")", "t", env)?
    assert_exprs_equal("(eqv? \"foo\" 'foo)", "nil", env)?
    assert_exprs_equal("(eqv? (cons 1 2) (cons 1 2))", "nil", env)?
    assert_exprs_equal("(eqv? pair pair)", "t", env)?
}

fun test_runtime_corelib_base_equal() {
    test_section("test_runtime_corelib_base_equal")
    test_expectation("it should return whether the given objects are structually equal")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    let pair = new_num(2)
    pair = new_cons(new_num(1), pair)
    env = env_define(env, new_symbol("pair"), pair)
    assert_exprs_equal("(equal? 1 1)", "t", env)?
    assert_exprs_equal("(equal? 1 2)", "nil", env)?
    assert_exprs_equal("(equal? \"foo\" \"foo\")", "t", env)?
    assert_exprs_equal("(equal? \"foo\" 'foo)", "nil", env)?
    assert_exprs_equal("(equal? (cons 1 2) (cons 1 2))", "t", env)?
    assert_exprs_equal("(equal? pair pair)", "t", env)?
}

fun test_runtime_corelib_base_quote() {
    test_section("test_runtime_corelib_base_quote")
    test_expectation("it should return an unevaluated argument")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    let list = new_nil()
    list = new_cons(new_symbol("b"), list)
    list = new_cons(new_symbol("a"), list)
    env = env_define(env, new_symbol("list"), list)
    assert_exprs_equal("(quote 1)", "1", env)?
    assert_exprs_equal("(quote t)", "t", env)?
    assert_exprs_equal("(quote nil)", "nil", env)?
    assert_exprs_equal("(quote (a b))", "list", env)?
}

fun test_runtime_corelib_base_cons() {
    test_section("test_runtime_corelib_base_cons")
    test_expectation("it should make a cons-cell")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    let pair = new_cons(new_text("a"), new_num(123))
    env = env_define(env, new_symbol("pair"), pair)
    assert_exprs_equal("(cons \"a\" 123)", "pair", env)?
}

pub fun test_runtime_corelib_base() {
    test_runtime_corelib_base_error()?
    test_runtime_corelib_base_exit()?
    test_runtime_corelib_base_eqv()?
    test_runtime_corelib_base_equal()?
    test_runtime_corelib_base_quote()?
    test_runtime_corelib_base_cons()?
}

main {
    test_runtime_corelib_base()?
}
