import * from "./error.ab"
import * from "./object.ab"
import * from "./env.ab"
import * from "./runtime_corelib.ab"
import * from "./testing.ab"
import * from "./eval_test_utils.ab"

fun test_runtime_corelib_base_error() {
    test_section("test_runtime_corelib_base_error")
    test_expectation("it should raise an error")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    assert_expr_raises_err("(error \"foo\")", code_user_error(), env)?
    assert_expr_raises_err("(error \"my_error\" \"foo\")", "my_error", env)?
}

fun test_runtime_corelib_base_exit() {
    test_section("test_runtime_corelib_base_exit")
    test_expectation("it should raise exit_interpreter")
    debug_clear_all_objects()
    let env = runtime_corelib_import(new_env())
    assert_expr_raises_err("(exit)", code_exit_interpreter(), env)?
}

main {
    test_runtime_corelib_base_error()?
    test_runtime_corelib_base_exit()?
}
