// Module corelib provides a core library for Amber.
import * from "./object.ab"
import * from "./env.ab"
import * from "./native.ab"
import * from "./eval.ab"
import * from "./runtime_corelib_base.ab"
import * from "./runtime_corelib_math.ab"
import * from "./runtime_corelib_list.ab"

pub fun runtime_corelib_import(env: Num): Num {
    env = runtime_corelib_base_import(env)
    env = runtime_corelib_math_import(env)
    env = runtime_corelib_list_import(env)
    return env
}
